# Generated by Django 5.2.7 on 2025-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Queue', 'Queue'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Aborted', 'Aborted')], default='Queue', max_length=20),
        ),
    ]
